name: Give me a heads-up.

on:
  schedule:
    - cron: '45 23 * * 1-5'

jobs:
  notice:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: npm install
    - shell: bash
      env: 
        FUSION_ID: ${{ secrets.FUSION_ID }}
        FUSION_PASSWORD: ${{ secrets.FUSION_PASSWORD }}
        SLACK_DEVELOPMENT_URL: ${{ secrets.SLACK_DEVELOPMENT_URL }}
        SLACK_PRODUCTION_URL: ${{ secrets.SLACK_PRODUCTION_URL }}
      run: |
        echo "{\"fusionId\": \"$FUSION_ID\", \"fusionPassword\": \"$FUSION_PASSWORD\", \"slackDevelopmentUrl\": \"$SLACK_DEVELOPMENT_URL\", \"slackProductionUrl\": \"$SLACK_PRODUCTION_URL\"}" > secret.json
    - run: npm start
